spring:
 datasource:
   url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF8
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: 021213
 mvc:
   view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp
jpa:
 database: Mysql
 show-sql: true
 hibernate:
  naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
