spring:
 datasource:
   url: jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF8
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: 123456
 mvc:
   view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp
 jpa:
  database: Mysql
  show-sql: true
  hibernate:
    use-new-id-generator-mappings: false
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
