spring:
 datasource:
   url: jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF8
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: 123456
   druid:
       #最大活跃数
    max-active: 20
       #初始化数量
    initial-size: 1
       #最大连接等待超时时间
    max-wait: 60000
       #打开PSCache，并且指定每个连接PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
#    validation-query-timeout:
    validation-query: select 1 from dual
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
       #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat
       #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
       #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
 mvc:
   view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp
 jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      use-new-id-generator-mappings: false
 servlet:
   multipart:
     max-file-size: 1024000 # 单个文件最大值
     max-request-size: 2048000
logging:
  level:
#  该包下的日志记录关闭
   com.bxz.controller: off